receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  debug:
    verbosity: detailed
      
extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines: 
    traces:
      receivers: [otlp]
      exporters: [otlphttp/tempo, debug]